### ISSUE TITLE
Change config to group sensors in a single calendarific integration

### ISSUE THREAD

**Issue by thundergreen** [pinkywafer/Calendarific#1]
I had to add all sensors separately via integration. nice would be a choice how many and which sensors of holidays we would like to add and bundle those inder ONE integration called Calendarific or so :)

**Comment by pinkywafer** [comment]
I'm going to think about this carefully before implementing any changes in this regard. But I do see your point, and am open to suggestions as to how such a configuration could be presented on the integrations screen.  I also appreciate that at the moment,  if you are using a lot of these sensors,  they would occupy a lot of space on the integrations list.
I think the best would be to leave it as is for the moment,  and keep this issue open for discussion as to the best way to present the configuration.

**Comment by pinkywafer** [comment]
Closing as there have been no further comments or suggestions,  and the current method of configuring each sensor is on line with other integrations in home assistant.
