### ISSUE TITLE
Naming of "days" between integrations

### ISSUE THREAD

**Issue by quiggles** [pinkywafer/Calendarific#10]
The calendarific integration uses the word "days" and the anniversaries integration uses "Days" - really minor but I like consistency! Otherwise thanks for the tools!

**Comment by pinkywafer** [comment]
"days" is now configurable in the anniversaries integration (this was done to allow people to use different languages as HA cannot translate unit_of_measurement)
I do intend to make this configurable here also, so I'll switch the default to "Days" for consistency at the same time
