### ISSUE TITLE
Calendarific stopped working

### ISSUE THREAD

**Issue by bandric1** [pinkywafer/Calendarific#12]
Is it api issue it stopped showing api key is ok calls are bellow 200/month data is unavalable.

**Comment by pinkywafer** [comment]
Please check the api calls again - I have just encountered this also.  My account page on calendarific shows 170/1000 calls made, but the View detailed usage metrics page shows that this shot up to 35000 calls on the 25th of the month.

This has showed up a bug where if an error is returned, the component continues querying the api.
Hotfix for the bug coming.

I'm afraid I can't say for sure how long it takes before the api releases an account which has gone over the limit yet, so I'll continue to keep this issue open for the moment.

**Comment by pinkywafer** [comment]
The other concern is that I cannot see what the error was that initially caused the sudden increase in calls, so will continue to monitor

**Comment by pinkywafer** [comment]
release 0.10.3 has this bugfix.

I'd recommend disabling the integration for the moment if your account has gone over the usage limit, or using an alternative account, until we know how long it takes for the usage ban to be lifted

**Comment by bandric1** [comment]
Hi sorry for slow response illness. Now its working back again after the last update.
