### ISSUE TITLE
API Limit Exceeded

### ISSUE THREAD

**Issue by PachangaDad** [pinkywafer/Calendarific#19]
Hi, 
Please be patient with me as I'm just beginning with my HA system.
My integration was working and stopped. I even took effort to rebuild another HA system and install your calendarific API and still get this as an error with new installation. When I check on the calendarific website and logon with my ID , I show only 56 requests out of 1000 total api requests allowance.

I'm baffled as to what is wrong. I am assuming the freebie account is viable. Any tips you can provide?
Thanks in advance

**Logger: custom_components.calendarific
Source: custom_components/calendarific/__init__.py:111
Integration: Calendarific (documentation)
First occurred: 12:09:38 PM (1 occurrences)
Last logged: 12:09:38 PM

API Limit Exceeded. Please upgrade your account. See https://calendarific.com/ for details.**

**Comment by pinkywafer** [comment]
you could check the graph. https://calendarific.com/usage.  I can only suggest that multiple restarts of home assistant have pushed you over the rate limit.  Sadly, as far as I can tell, there is no way to reset the api usage, and so far (from my own testing) The api limit does not appear to ever reset.  I have emailed the calendarific team in the past, but have never received a reply.
The only suggestion I could give is to create a new api key by opening a new account with a different email address

**Comment by PachangaDad** [comment]
Thanks for the reply. As you can see it's very low.

Thanks again
![2021-01-27_16-10-09](https://user-images.githubusercontent.com/20826608/106055173-0856f700-60bb-11eb-9d55-59981121378e.png)

**Comment by pinkywafer** [comment]
That does look fine, sorry I'm not able to help. I did have the same when I was doing lots of testing, but the graph did show all the api calls, do I'm not sure why this has happened

**Comment by gdreelin** [comment]
@pinkywafer I am getting the same thing here too. I deleted the install and redid it but now it does not like the API key to complete the install. I am asking the Calendarific to see if I can get a new key.

**Comment by sihartley** [comment]
@pinkywafer @PachangaDad I am having this exact same issue, was there ever a fix for this? Did creating a new account work, or was that just a futile exercise?

**Comment by pfunkmallone** [comment]
I'm having the same issue as of a few weeks ago. This appears to result in sensor states of "unknown"
