### ISSUE TITLE
Feature request: Add sensor dates to the Home Assistant calendar

### ISSUE THREAD

**Issue by pfunkmallone** [pinkywafer/Calendarific#20]
It would be nice to have them added to the HA calendar. Perhaps this project can help:

https://github.com/bruxy70/Garbage-Collection/blob/development/custom_components/garbage_collection/calendar.py

**Comment by Techwolf12** [comment]
+1, am surprised it is not in there yet. Would be a nice feature. @pinkywafer Are you open for pull requests on this? If so, I will check if I have time within a month or so to implement this.

**Comment by pinkywafer** [comment]
Thanks @Techwolf12, yes I'm definitely open to PRs and I would be most grateful - I would have liked to already have done this, but have just not had the free time I used to have (also why my last YouTube video was now 15 months ago!)

**Comment by mclever** [comment]
@Techwolf12 were you able to make some progress on this? I like the idea of combining the garbage collection and the auto holidays.

**Comment by dcmeglio** [comment]
@Techwolf12 @pinkywafer did you ever get anywhere with this?
