### ISSUE TITLE
Getting API Limit Exceeded Errors but not exceeding limit

### ISSUE THREAD

**Issue by Snuffy2** [pinkywafer/Calendarific#28]
In the past few days (looks like since 5/24), the Calendarific integration entries have been showing as unavailable and I've been getting API Limit exceeded errors. I am on the free plan, but looking at my account usage, I don't believe I am exceeding the limit at all. It's 1,000 requests per month, right?

```
This error originated from a custom integration.

Logger: custom_components.calendarific
Source: custom_components/calendarific/__init__.py:111
Integration: Calendarific (documentation)
First occurred: 12:52:02 PM (1 occurrences)
Last logged: 12:52:02 PM

API Limit Exceeded. Please upgrade your account. See https://calendarific.com/ for details.
```
![2022-05-28_15-34-21](https://user-images.githubusercontent.com/6526076/170840408-8f50c059-7f32-4370-a49f-012fe1e76206.png)
![2022-05-28_15-34-19](https://user-images.githubusercontent.com/6526076/170840409-56ee6238-5560-4130-9a3d-1970ea7678a6.png)
<img width="1261" alt="2022-05-28_15-45-23 259" src="https://user-images.githubusercontent.com/6526076/170840692-c5a0daec-cad0-4c8f-b288-fba70f0bbfed.png">

**Comment by Snuffy2** [comment]
I'm still not able to get the integration fixed and still getting the API limit error. Any ideas how to further troubleshoot?

**Comment by asucrews** [comment]
@Snuffy2 isn't the free plan 1000 Requests / mo? https://calendarific.com/pricing

**Comment by Snuffy2** [comment]
@asucrews, you are likely correct, it is probably 1000/month. But, if you look at the api documentation (https://calendarific.com/api-documentation), it says 1000/day which may be a typo. 

However, I am still not able to get it to work. Everytime HA restarts, I get the error above and all of my holiday entities still report as Unavailable. Sounds like I may be the only one though. Maybe I'll just remove the integration, create a new API account and set it up again.

**Comment by Snuffy2** [comment]
I created a new Calendarific API account and now everything is working fine. Not sure what was wrong with my old account but it's working again.
