### ISSUE TITLE
Holidays not available

### ISSUE THREAD

**Issue by cariboo907** [pinkywafer/Calendarific#3]
On the Calendarific integration page not all the holidays listed on https://calendarific.com/holidays/2020/ca are listed. I live in British Columbia, Canada.

**Comment by pinkywafer** [comment]
I'll investigate later, but expect this could be due to state being required

**Comment by pinkywafer** [comment]
I have checked. Canada does support state codes, so you will only receive holidays which apply to ALL states unless you add a state code, i.e. ca-nt
List of state codes for Canada: https://en.m.wikipedia.org/wiki/ISO_3166-2:CA
