### ISSUE TITLE
Add support to change icon color

### ISSUE THREAD

**Issue by sycorhsx** [pinkywafer/Calendarific#31]
As it is I had to create a new theme just for this one card.  Granted I'm kind of new to HA so I could just be making my life harder.  But the ability to change the icon color based on various factors would be nice.  Or even just a default change.  Also, changing font and size doesn't seem to work.  I was able to change the font with a theme adjustment, but not the font size, but again, that could just be my ignorance.

**Comment by pinkywafer** [comment]
beyond the scope of an integration - color is not controlled by the integrations, it is controlled by the front-end (ie. theme, cards etc)
