### ISSUE TITLE
"please upgrade your account" while API key is correct and not out of 'allowance'

### ISSUE THREAD

**Issue by jeroenterheerdt** [pinkywafer/Calendarific#32]
Suddenly my Calendarific install errors out with an "Please upgrade your account" message from Calendarific. I regenerated my API key twice already and confirmed its correct in the configuration.yaml. Also confirmed I have not exceeded the maximum number of API requests according to the Calendarific website.
Any idea what might be causing this?

HA version:2022.10.0, latest version of Calendarific component.

**Comment by Snuffy2** [comment]
I've had the same issue more than once (see #28). It seems that once you exceed the API limit (at least for the free plan), it never resets again. This appears to be a Calendarific issue and not the Home Assistant integration. Ultimately, I just registered for a new Calendarific API account, used the new API, and it worked.

**Comment by jeroenterheerdt** [comment]
thanks, that worked. weird issue though, but clearly a Calendarific issue.
