### ISSUE TITLE
0.109 has warning about doing I/O inside event loop

### ISSUE THREAD

**Issue by Shaun-Harrison** [pinkywafer/Calendarific#6]
From the log file

     Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for calendarific doing I/O at custom_components/calendarific/__init__.py, line 143: response = requests.get(url, params=parameters);

**Comment by pinkywafer** [comment]
Duplicate of #5

**Comment by pinkywafer** [comment]
Looking into this... not certain of the work around yet

**Comment by pinkywafer** [comment]
Issue still persists in 0.10.0

**Comment by pinkywafer** [comment]
Still present at update
